- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
Makes info in part catalog more descriptive
> Add plural switcher description option

- B9PartSwitch/B9PartSwitch.csproj
- B9PartSwitch/Configs/CFGUtil.cs
- B9PartSwitch/Configs/CFGUtilObject.cs
- B9PartSwitch/Configs/CFGUtilPartModule.cs
- B9PartSwitch/Configs/ConfigField.cs
- B9PartSwitch/Configs/ConfigFieldList.cs
- B9PartSwitch/Configs/ParseType.cs
- B9PartSwitch/Exceptions.cs
- B9PartSwitch/Extensions/AttachNodeExtensions.cs
- B9PartSwitch/Extensions/CFGUtilPartModuleExtensions.cs
- B9PartSwitch/Extensions/ListExtensions.cs
- B9PartSwitch/Extensions/ObjectExtensions.cs
- B9PartSwitch/Extensions/PartExtensions.cs
- B9PartSwitch/Extensions/PartModuleExtensions.cs
- B9PartSwitch/Extensions/TypeExtensions.cs
- B9PartSwitch/FARChecker.cs
- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
- B9PartSwitch/PartSwitch/PartSubtype.cs
- B9PartSwitch/Serialization/ConfigNodeSerialized.cs
- B9PartSwitch/Serialization/SerializedDataContainer.cs
- B9PartSwitch/TankSettings/B9TankSettings.cs
- B9PartSwitch/TankSettings/Tanks.cs
- B9PartSwitch/Test/ModuleB9PartSwitchTest.cs
* Subtype is now found intelligently
* Subtype name is first priority
* If index was previously set that is second priority
* Next, try to infer subtype based on resources
* Finally, just use first one
* A lot of internal adjustments to how things are found
* Get rid of unnecessary logging and using directives
> Refactor Switching

- B9PartSwitch/B9PartSwitch.csproj
- B9PartSwitch/Extensions/IEnumerableExtensions.cs
- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
- B9PartSwitch/PartSwitch/PartSubtype.cs
> Don't memoize

- B9PartSwitch/Extensions/PartExtensions.cs
- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
- B9PartSwitch/PartSwitch/PartSubtype.cs
* Allow a "child" module to modify the volume of the parent
* Allow mutliple modules to manage the same transform or node.  It will be enabled if they all think it should.
> Cross Module Stuff

- B9PartSwitch/PartSwitch/PartSubtype.cs
- B9PartSwitch/PartSwitch/SubtypePartFields.cs
> Add stackSymmetry to part fields

- .travis.yml
Instability of recent versions leaves me wanting to keep it versioned, but this one seems to work
> Use mono 5.4.1

- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
- B9PartSwitch/PartSwitch/PartSubtype.cs
- B9PartSwitch/PartSwitch/PartSwitchFlightDialog.cs
Also add option for subtypes to not be allowed in flight
Resolves #56
> Always empty tanks when switching in flight

- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
> Option for switcher to be advanced tweakables only

- B9PartSwitch/B9PartSwitch.csproj
- B9PartSwitch/FatalErrorHandler.cs
- B9PartSwitch/Fishbones/NodeDataList.cs
- B9PartSwitch/Fishbones/NodeDataListLibrary.cs
- B9PartSwitch/TankSettings/B9TankSettings.cs
> Handle fatal errors

- B9PartSwitch/PartSwitch/PartSubtype.cs
> Only match on exact node IDs

- B9PartSwitch/B9PartSwitch.csproj
- build_script/script/make_release.sh
> Move copying DLL into .csproj

- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
- B9PartSwitch/PartSwitch/PartSwitchFlightDialog.cs
- GameData/B9PartSwitch/Localization/en-us.cfg
> Allow localization of hard-coded strings

- B9PartSwitch/Extensions/PartExtensions.cs
Get exceptions when copying a part otherwise.  Delta-v calcs were also probably broken.
> Also add simulation resource when adding a resource

- B9PartSwitch/PartSwitch/AttachNodeModifierInfo.cs
- B9PartSwitch/PartSwitch/AttachNodeMover.cs
- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
- B9PartSwitch/PartSwitch/PartSubtype.cs
- B9PartSwitch/PartSwitch/SubtypePartFields.cs
* Stack nodes now respect `scale`, `rescaleFactor`, and TweakScale (Resolves #118)
* Surface attach node now respects `scale` and `rescaleFactor`
> Scale attach node movers

- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
Turns out this is a valid use case.  We want to allow this, provide some indication that there is a locked switcher, but also disable the switching GUI.  So the switching options are replaced with a fixed indicator.
Done based on feedback in #114
Resolves #114
> Better handling for a single subtype

- B9PartSwitch/B9PartSwitch.csproj
- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
- B9PartSwitch/PartSwitch/ModuleModifierInfo.cs
- B9PartSwitch/PartSwitch/PartModifiers/IModuleDataHandler.cs
- B9PartSwitch/PartSwitch/PartModifiers/ModuleDataHandlerBasic.cs
- B9PartSwitch/PartSwitch/PartModifiers/ModuleDataHandlerModuleEnginesFX.cs
- B9PartSwitch/PartSwitch/PartModifiers/ModuleDataLoader.cs
- B9PartSwitch/PartSwitch/PartModifiers/ModuleDeactivator.cs
- B9PartSwitch/PartSwitch/PartSubtype.cs
Implements basic parts of #100 without most of the module specifics
> Initial implementation of module switching

- B9PartSwitch/UI/UIPartActionSubtypeSelector.cs
Since subtypes might be skipped, real subtype and button indices don't line up
Resolves #173
> Fix switcher with tech restrictions

- B9PartSwitch/B9PartSwitch.csproj
- B9PartSwitch/PartSwitch/PartModifiers/AttachNodeMover.cs
- B9PartSwitch/PartSwitch/PartModifiers/IPartAspectLock.cs
- B9PartSwitch/PartSwitch/PartModifiers/IPartModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartAttachNodeModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartCenterOfBuoyancyModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartCenterOfDisplacementModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartCoLOffsetModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartCoMOffsetModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartCoPOffsetModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartCrashToleranceModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartMaxTempModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartModifierBase.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartSkinMaxTempModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/PartStackSymmetryModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/ResourceModifier.cs
- B9PartSwitch/PartSwitch/PartModifiers/TextureReplacement.cs
- B9PartSwitch/PartSwitch/PartModifiers/TransformRotator.cs
- B9PartSwitch/PartSwitch/PartSubtype.cs
Modifiers that don't lock don't need to be concerned anymore
Resolves #181
> Tie part aspect locks to their own interface

- GameData/B9PartSwitch/Localization/zh-cn.cfg
> Add "zh-cn.cfg"

- GameData/B9PartSwitch/Localization/de-de
> German Localization

- .github/workflows/build-and-test.yml
various improvements
release stuff probably can't be tested until the next release
> Fix up actions

- .github/workflows/build-and-test.yml
seems to be needed per https://github.com/aws/aws-cli/issues/5234
> put region on all aws commands

- B9PartSwitch/Extensions/PartExtensions.cs
- B9PartSwitch/ModuleMatcher.cs
- B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
- B9PartSwitch/PartSwitch/ModuleModifierInfo.cs
- B9PartSwitch/PartSwitch/PartModifiers/ModuleDeactivator.cs
- B9PartSwitch/PartSwitch/PartSubtype.cs
- B9PartSwitch/Utils/ColorParser.cs
- B9PartSwitchTests/Fishbones/NodeDataListBuilderTest.cs
- B9PartSwitchTests/Fishbones/Parsers/NodeObjectWrapperIContextualNodeTest.cs
> Fix some warnings

- GameData/B9PartSwitch/Localization/it-it.cfg
Hello @blowfishpro! With this PR I'd like to add italian localization. I take the opportunity to thank you for the mod :)
> Add italian localization
