B9PartSwitch/PartSwitch/ModuleB9PartInfo.cs

KSP explodes when you have const fields on a PartModule because it tries
to copy fields from one object to another on the root part without
checking the fields first.
http://bugs.kerbalspaceprogram.com/issues/9865

Put constants in a nested class

---

.travis.yml
build_script/install/install_ksp_dlls.sh

Easier to deal with this way, and supports multiple projects

Reference KSP DLLs rather than moving them

---

B9PartSwitch/B9PartSwitch.csproj
build_script/script/assembly_info.rb

Windows needs sh command somewhere
Also add better logging to AssemblyInfo generation

Unify AssemblyInfo on Windows and unix-like

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/ModuleB9DisableTransform.cs

This will be used by old wheels in B9 once they are converted to KSPWheel - there is a bounds collider that needs to be removed.

Add transform disabling module

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/packages.config
B9PartSwitchTests/B9PartSwitchTests.csproj
B9PartSwitchTests/packages.config

This seems to work on all platforms tested.  Building on OSX must use MSBuild and building in Travis CI must use xbuild, so some inconsistency there, but otherwise seems to work

Use roslyn as the compiler

---

NetKAN/B9PartSwitch.netkan

A future DeadSkins release is going to change from their current texture switching methods to a mesh switching method which can be achieved by B9PartSwitch. Adding this provide to B9PartSwitch will get things ready for that future change.

Add virtual mod provides

---

B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs

Resolves #71 
Solution was to keep track of the original manually and then tell it to re-apply its texture switches in `OnAwake` rather than `OnCopy`

Fix drag cubes resetting texture switch

---

B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs

The active subtype should be done last, otherwise transforms that should
be enabled might not be

Fix order that subtypes are (de)activated for icon

---

B9PartSwitch/PartSwitch/TextureSwitchInfo.cs

It should only look at the current GameObject for `transform`,
`baseTransform` is used if you also want children

Fix transform in a TEXTURE node lookin for renderers in children

---

B9PartSwitch/PartSwitch/PartSubtype.cs

If a part up the hierarchy gets its drag cubes rendered when loading a
craft, the texture switches will be activated by the process of creating
the drag cube clone (deactivated before the clone and then activated
after), then Start is called on this part which re-initializes the
texture switches.  The original information is lost and the texture
switch is now locked in.

Deactivate texture switches before re-initializing

---

B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs

It'll be localized, whereas the pure name will not
Resolves #79

Use resource display name when generating info

---

B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs

This workaround was introduced in 8c8fe28 and is fixed in KSP 1.4.3
Resolves #45

Revert hack fix for map object disappearing

---

B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/PartSwitch/PartSubtype.cs

New methods exist in KSP 1.4.3 that allow an alternate fix to
#71 - this is much less hacky, performance wasting, and error prone

Remove hacky serialization hooks

---

B9PartSwitch/Extensions/PartExtensions.cs
B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs

Create a copy of the fairing object on the attached part, then move the real one back to the actual part and hide it.  The model ends up in the same state as when the part starts with the fairing already jettisoned.
Resolves #85

Fix ModuleJettison fairing disappearing

---

.travis.yml

These rarely need to be accessed and can be rebuilt if needed.  High availability is not needed.
That's Infrequent Access - Single Availability Zone

use ONEZONE_IA s3 storage for dev builds

---

B9PartSwitch/CustomPartModule.cs
B9PartSwitch/FatalErrorHandler.cs
B9PartSwitch/Fishbones/FieldWrappers/FieldWrapper.cs
B9PartSwitch/Fishbones/FieldWrappers/IFieldWrapper.cs
B9PartSwitch/Fishbones/FieldWrappers/PropertyWrapper.cs
B9PartSwitch/Fishbones/NodeDataField.cs
B9PartSwitch/Fishbones/NodeDataList.cs
B9PartSwitch/Fishbones/NodeDataListLibrary.cs
B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/PartSwitch/PartSubtype.cs
B9PartSwitch/TankSettings/B9TankSettings.cs
B9PartSwitchTests/Fishbones/FieldWrappers/FieldWrapperTest.cs
B9PartSwitchTests/Fishbones/FieldWrappers/PropertyWrapperTest.cs
B9PartSwitchTests/Fishbones/NodeDataFieldTest.cs
B9PartSwitchTests/Fishbones/NodeDataListTest.cs

Resolves #95 
And then some...
Fatal errors should provide a lot more context now, both in the dialog and in the log.  Additional fatal errors when:
* Switcher has less than two subtypes
* Subtype names are duplicated
* Subtype has no name
* Modules conflict (not until you try to add the part to the editor)

Better exception handling

---

templates/B9PartSwitch.version.erb

One of the lines from the old implementation of KSP_VERSION got left behind.

Fix version file syntax error (extra close brace)

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/PartSwitch/PartSubtype.cs
B9PartSwitch/SeriousWarningHandler.cs

User still gets an on-screen message but it can be dismissed without quitting the game
* Subtypes with no name
* Duplicate subtype names
These may become errors again at some point in the future but for now it's probably better to give some time for them to be fixed

Downgrade some errors to serious warnings

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/Fishbones/Parsers/Exceptions.cs
B9PartSwitch/Fishbones/Parsers/PartResourceDefinitionValueParser.cs
B9PartSwitch/Fishbones/Parsers/ValueParseMap.cs
B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/packages.config
B9PartSwitchTests/B9PartSwitchTests.csproj
B9PartSwitchTests/Fishbones/FieldWrappers/FieldWrapperTest.cs
B9PartSwitchTests/Fishbones/FieldWrappers/PropertyWrapperTest.cs
B9PartSwitchTests/Fishbones/NodeDataMappers/NodeListMapperTest.cs
B9PartSwitchTests/Fishbones/NodeDataMappers/NodeScalarMapperTest.cs
B9PartSwitchTests/Fishbones/NodeDataMappers/ValueListMapperTest.cs
B9PartSwitchTests/Fishbones/Parsers/DefaultValueParseMapTest.cs
B9PartSwitchTests/Fishbones/Parsers/EnumValueParserTest.cs
B9PartSwitchTests/Fishbones/Parsers/NodeObjectWrapperTest.cs
B9PartSwitchTests/TestUtils/AssertUtilTest.cs
B9PartSwitchTests/app.config
B9PartSwitchTests/packages.config
bin/test

It works with the main assembly being .NET 3.5, it may be the case that tests are being run against .NET 4 runtimes anyway.  I don't really anticipate this causing any false positives/negatives in tests

Use .NET 4 in test assembly

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/PartSwitch/AttachNodeModifierInfo.cs
B9PartSwitch/PartSwitch/AttachNodeMover.cs
B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/PartSwitch/PartSubtype.cs

One switcher can manage each node's position.  Subtypes that don't specify
any will use the original position.  To manage an attach node's postion
within a subype you would include a node like this:
```
NODE
{
name = top01 // attach node id
position = 0, 1, 0 // x,y,z position
}
```

Allow moving attach nodes

---

B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs

Doesn't show up right in the log

Fix error message for duplicate subtype names

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/ModuleB9PropagateCopyEvents.cs
B9PartSwitch/PartSwitch/TextureSwitchInfo.cs
GameData/B9PartSwitch/CopyEventsPropagator.cfg

* `OnWillBeCopied` and `OnWasCopied` weren't being fired for child parts of the one being cloned, this lead to them not getting their textures properly reset
* Inactive renderers were being excluded, causing texture switches to not be initialized on disabled transforms after copying a part.

Fix texture switch when copying parts

---

.travis.yml
bin/install-ksp-dlls
build_script/install/install_ksp_dlls.sh

The Google Drive package was getting too big, it makes you go through a confirmation step to download it.  This is simpler.  Make some improvements to how things are organized.

Download KSP DLLs from S3

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/PartSwitch/PartModifiers/AttachNodeToggler.cs
B9PartSwitch/PartSwitch/PartModifiers/IPartModifier.cs
B9PartSwitch/PartSwitch/PartModifiers/PartModifierBase.cs
B9PartSwitch/PartSwitch/PartModifiers/TextureReplacement.cs
B9PartSwitch/PartSwitch/PartModifiers/TransformMover.cs
B9PartSwitch/PartSwitch/PartModifiers/TransformRotator.cs
B9PartSwitch/PartSwitch/PartSubtype.cs
B9PartSwitch/PartSwitch/TransformModifierInfo.cs

* Clean up reinitialize hook and split into active and inactive
* Subtypes handle volume, cost, mass without error pre-initialization
* Eliminate initialization in OnLoad for instance (wait until start)
* Allow moving and rotating transforms
* Subtypes now allow `TRANSFORM` nodes, with `name =` transform name, `positionOffset`, `rotationOffset`

Move transforms

---

B9PartSwitch/Localization.cs
B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/PartSwitch/PartSwitchFlightDialog.cs
GameData/B9PartSwitch/Localization/en-us.cfg

* Add the following fields:
* `showPreviousSubtypeAction` (default false)
* `showNextSubtypeAction` (default false)
* Add the following action groups
* Switch Subtype
* Shows window with list of subtypes
* Vislible if switchInFlight is true and there is at least one subtype allowing switch in flight
* Next Subtype
* Goes to the next subtype
* Shows warning if resources will be removed
* Visible if `switchInFlight` is true, `showNextSubtypeAction` is true, and at least one subtype allows switching in flight
* PreviousSubtype
* Goes to the next subtype
* Shows warning if resources will be removed
* Visible if `switchInFlight` is true, `showPreviousSubtypeAction` is true, and at least one subtype allows switching in flight
* Adds the following localization keys (currently only `en-us`):
* …

Switch in flight action groups

---

B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/PartSwitch/PartSubtype.cs

Defined on the subtype - if set, when placing parts in mirror symmetry in the editor, it will use this subtype for the symmetry counterparts

Add mirrorSymmetrySubtype field

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/Extensions/PartExtensions.cs
B9PartSwitch/Fishbones/NodeDataObjectExtensions.cs
B9PartSwitch/Fishbones/Parsers/DefaultValueParseMap.cs
B9PartSwitch/Localization.cs
B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/PartSwitch/PartModifiers/ResourceModifier.cs
B9PartSwitch/PartSwitch/PartSubtype.cs
B9PartSwitch/PartSwitch/PartSwitchFlightDialog.cs
B9PartSwitch/TankSettings/Tanks.cs
B9PartSwitch/UI/PrefabManager.cs
B9PartSwitch/UI/SwitcherSubtypeDescriptionGenerator.cs
B9PartSwitch/UI/TooltipHelper.cs
B9PartSwitch/UI/UIPartActionSubtypeButton.cs
B9PartSwitch/UI/UIPartActionSubtypeSelector.cs
B9PartSwitch/UI/UI_SubtypeSelector.cs
B9PartSwitch/Utils/ColorParser.cs
B9PartSwitch/Utils/GroupedStringBuilder.cs
B9PartSwitch/Utils/ResourceColors.cs
B9PartSwitchTests/B9PartSwitchTests.csproj
B9PartSwitchTests/Utils/ColorParserTest.cs
B9PartSwitchTests/Utils/GroupedStringBuilderTest.cs
GameData/B9PartSwitch/DefaultTankTypes.cfg
GameData/B9PartSwitch/Localization/en-us.cfg

* Implement new switching UI based on the stock variant switcher
* Have subtype switching buttons show some info about the subtype being switched to in a tooltip
* By default shows resources (including parent), mass, cost, max temperature, max skin temperature, crash tolerance
* Also shows `descriptionSummary` and `descriptionDetail` from subtype, before and after auto-generated info respectively, if present
* 4 new fieds on `SUBTYPE`
* `descriptionSummary` - any info here will be put in the subtype switching tooltip before the auto-generated info - make it brief
* `descriptionDetail` - any info here will be put in the subtype switching tooltip after the auto-generated info - go nuts
* `primaryColor` - color to use in the left part of the switching button
* if not specified, use the tank …

Improve UI

---

B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/UI/UIPartActionSubtypeSelector.cs

if module has `bottomOfWindow = false`, do not move it to the bottom of the PAW
Resolves #158

Allow switching ui to not be moved to bottom of PAW

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/Fishbones/Parsers/OverrideValueParseMap.cs
B9PartSwitch/Fishbones/Parsers/ScaleParser.cs
B9PartSwitch/PartSwitch/PartModifiers/TransformScaleModifier.cs
B9PartSwitch/PartSwitch/TransformModifierInfo.cs
B9PartSwitchTests/B9PartSwitchTests.csproj
B9PartSwitchTests/Fishbones/Parsers/OverrideValueParseMapTest.cs
B9PartSwitchTests/Fishbones/Parsers/ScaleParserTest.cs

`TRANSFORM {}` nodes now accept a `scaleOffset` value which is the relative local scale of the model (multiplicative on each axis).  It can either be a single number which is applied to all 3 axes or a 3 numbers applied to x, y, z and separated by spaces, tabs, or commas
Resolves #145

Allow transforms to be scaled

---

B9PartSwitch/PartSwitch/PartModifiers/AttachNodeMover.cs

When a part moves itself due to a node offset, that wasn't respecting the part's rotation
Fixes #160

Attach node offsets respect part rotation

---

B9PartSwitch/PartSwitch/PartModifiers/TextureReplacement.cs
B9PartSwitch/PartSwitch/TextureSwitchInfo.cs

The original would reset itself before the copy was initialized, so the copy would have no way of knowing about the original texture, and the switched texture would get stuck
Resolves #156

Fix texture switch sticking

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/PartSwitch/ModuleModifierInfo.cs
B9PartSwitch/PartSwitch/PartModifiers/ModuleOutputResourceResetter.cs

`ModuleDeployableSolarPanel` won't attempt to reinitialize the output resource if one already exists

Clear output resources before changing solar panel charge rate

---

B9PartSwitch/PartSwitch/PartModifiers/TextureReplacement.cs

it'll be instantiated when it needs to be
right now after a part is copied, the active subtype is re-instantiating the material, but other subtypes are still referencing the old material which will be unused at that point
so instead we just call renderer.material every time, which will instantiate when necessary
Resolves #174

texture modifiers only keep track of renderer, not material

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/PartSwitch/ModuleModifierInfo.cs
B9PartSwitch/PartSwitch/PartModifiers/ColorPropertyModifier.cs
B9PartSwitch/PartSwitch/PartModifiers/FloatPropertyModifier.cs
B9PartSwitch/PartSwitch/PartModifiers/IPartModifier.cs
B9PartSwitch/PartSwitch/PartModifiers/ModuleDataHandlerBasic.cs
B9PartSwitch/PartSwitch/PartModifiers/ModuleDeactivator.cs
B9PartSwitch/PartSwitch/PartModifiers/ModuleOutputResourceResetter.cs
B9PartSwitch/PartSwitch/PartModifiers/PartModifierBase.cs
B9PartSwitch/PartSwitch/PartModifiers/TextureReplacement.cs
B9PartSwitch/PartSwitch/PartModifiers/TransformMover.cs
B9PartSwitch/PartSwitch/PartModifiers/TransformRotator.cs
B9PartSwitch/PartSwitch/PartModifiers/TransformScaleModifier.cs
B9PartSwitch/PartSwitch/PartModifiers/TransformToggler.cs
B9PartSwitch/PartSwitch/PartSubtype.cs
B9PartSwitch/Utils/ChangeTransactionManager.cs
B9PartSwitchTests/B9PartSwitchTests.csproj
B9PartSwitchTests/Utils/ChangeTransactionManagerTest.cs

* Only call reinitialize lifecycle methods on modules that need it (those where not doing so would cause the resource to become unidentifyable)
* Ensure that reinitialization happens at the end of a switch cycle, not during it
* Send `ModuleDataChanged` to modules that have had their data changed
* Include two attributes in the event details, `requestNotifyFARToRevoxelize` and `requestRecalculateDragCubes`, which can be used to request FAR/drag cubes updates at the end of the cycle
* Transform move/rotation/scale now affect drag cubes/FAR
* Do aero updates in `OnStartFinished`
* Eliminates need for special logic for root part in flight
* Eliminates last part logic
* Send/listen for `DragCubesWereRecalculated` and `FarWasNotifiedToRevoxelize` to make sure actions are only done once per …

Support other modules updating the part's model

---

B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs

* Preserve drag cube weights when recalculating drag cubes
* Don't call drag cube update methods that will be called by the flight integrator anyway
* Ensure drag cubes aren't recalculated in flight regardless of configuration (it breaks things) (#124)

Drag cube fixes

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/Extensions/PartExtensions.cs
B9PartSwitch/Extensions/TransformExtensions.cs
B9PartSwitch/Fishbones/Parsers/DefaultValueParseMap.cs
B9PartSwitch/PartSwitch/AttachNodeModifierInfo.cs
B9PartSwitch/PartSwitch/MaterialModifierInfo.cs
B9PartSwitch/PartSwitch/ModuleModifierInfo.cs
B9PartSwitch/PartSwitch/PartModifiers/AttachNodeMover.cs
B9PartSwitch/PartSwitch/PartModifiers/AttachNodeSizeModifier.cs
B9PartSwitch/PartSwitch/PartSubtype.cs
B9PartSwitch/PartSwitch/TextureSwitchInfo.cs
B9PartSwitch/PartSwitch/TransformModifierInfo.cs
B9PartSwitch/Utils/StringMatcher.cs
B9PartSwitchTests/B9PartSwitchTests.csproj
B9PartSwitchTests/Fishbones/Parsers/DefaultValueParseMapTest.cs
B9PartSwitchTests/Utils/StringMatcherTest.cs

* Implement node size modifier
* `SUBTYPE` -> `NODE` -> `size`
* Accepts integers
* Will be scaled and rounded by TweakScale
* Allow more flexible matching of various names
* If it starts and ends with /, treat it as a regular expression
* If it contains * or ?, treat those as wildcards (anything or one character respectively)
* Otherwise treat it as a normal string
* If it starts with `\`, the next character is `/`, and it ends with `/`, eliminate the leading `\`
* Use in the following places:
* attach node modifier node name (`SUBTYPE` -> `NODE` -> `name`)
* transform toggle name (`SUBTYPE` -> `transform`)
* node toggler name (`SUBTYPE` -> `node`)
* material modifier transform names (`SUBTYPE` -> `MATERIAL` -> `transform`/`baseTransform`)
* texture modifier transform names (`SUBTYPE` -> …

Attach node size and more flexible matching

---

B9PartSwitch/B9PartSwitch.csproj
B9PartSwitch/Extensions/PartModuleExtensions.cs
B9PartSwitch/ModuleB9AssignUiGroups.cs
B9PartSwitch/ModuleMatcher.cs
B9PartSwitch/PartSwitch/ModuleB9PartSwitch.cs
B9PartSwitch/PartSwitch/ModuleModifierInfo.cs

* Allow `ModuleB9PartSwitch` to have its fields and events placed in a group:
* `uiGroupName` - unique identifier of the group
* `uiGroupDisplayName` - human readable name of the group to show in the UI
* New module for assigning PAW groups on other modules: `ModuleB9AssignUiGroups`
* takes one or more `MODULE` nodes that each identify a module to have its UI group assigned
* each one must have an `IDENTIFIER` node to identify the module
* it must have a `name` which is the name of the module (wildcards and regex are allowed)
* it can have any other fields that uniquely identify the module
* This is the same as the `IDENTIFIER` in a module switcher
* `uiGroupName` - unique identifier of the group
* `uiGroupDisplayName` - human readable name of the group to show in the UI
* only applies to …

Part action window groups

---

B9PartSwitch/PartSwitch/ModuleB9PartInfo.cs

Fixes the weird exceptions happening inside TweakScale (and potentially other add'ons) by reverting to the editor and other situations where the current craft is destroyed and a new instance is created.

Fixes https://github.com/net-lisias-ksp/TweakScale/issues/168 :)

---

B9PartSwitch/PartSwitch/PartSubtype.cs

`MaybeAddModifier` added an object to the list instead of the field in the object. This prevented `maxTemp`, `skinMaxTemp` and `crashTolerance` from being displayed in the tooltip of switches.

Fix bug in MaybeAddModifier preventing maxTemp changes from being displayed
